services:
  - type: web
    name: unified-legal-system-backend
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        value: mongodb+srv://pcharithasree13_db_user:Cherry1113@start-up-crm-lite.njma2fj.mongodb.net/unified-legal-system?retryWrites=true&w=majority
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: USE_MOCK_DB
        value: "false"
